import { useMemo, useState } from "react";
import { Menu, ArrowUpRight, ChevronRight, Play, Mail, Phone, MapPin, Instagram, Facebook, X, Check, Upload, Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import heroImage from "@/assets/hero-luxury-home.jpg";
import property1 from "@/assets/property-1.jpg";
import property2 from "@/assets/property-2.jpg";
import property3 from "@/assets/property-3.jpg";
import furniture1 from "@/assets/furniture-1.jpg";
import furniture2 from "@/assets/furniture-2.jpg";
import furniture3 from "@/assets/furniture-3.jpg";
import logo from "@/assets/wsl-logo.png";

const properties = [
  { id: "01", name: "The Meridian House", location: "Maitama, Abuja", type: "Detached residence", price: "₦185,000,000", image: property1, features: ["Smart Home", "Premium Finishes"] },
  { id: "02", name: "Aster Court", location: "Gwarinpa, Abuja", type: "4-bedroom terrace", price: "₦95,000,000", image: property2, features: ["Fully Furnished", "Premium Finishes"] },
  { id: "03", name: "The Palm Residence", location: "Jabi, Abuja", type: "3-bedroom apartment", price: "₦72,000,000", image: property3, features: ["Smart Home", "Fully Furnished"] },
];
const stages = ["Foundation", "Block Work", "Ceiling", "Windows", "Finishing", "Handover"];
const media = [furniture1, furniture2, furniture3, property1, property2, property3];

function SectionIntro({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) { return <div className="section-intro"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{text && <p>{text}</p>}</div> }
function Nav({ onNavigate }: { onNavigate: (id: string) => void }) { const links = [["Home", "home"], ["About Us", "about"], ["Properties", "properties"], ["Previous Jobs", "jobs"], ["Project Updates", "updates"], ["Contact", "contact"]]; return <header className="site-header"><a className="wordmark" href="#home" onClick={() => onNavigate("home")}><img src={logo} alt="WSL Properties" /><span>WSL <b>PROPERTIES</b></span></a><nav className="desktop-nav">{links.map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => onNavigate(id)}>{label}</a>)}</nav><Sheet><SheetTrigger asChild><Button variant="ghost" size="icon" className="mobile-menu"><Menu /></Button></SheetTrigger><SheetContent><nav className="mobile-nav">{links.map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => onNavigate(id)}>{label}<ChevronRight size={16}/></a>)}</nav></SheetContent></Sheet><Button className="header-cta" onClick={() => onNavigate("contact")}>Enquire <ArrowUpRight size={16}/></Button></header> }

export default function Index() {
  const [selectedStage, setSelectedStage] = useState(1); const [gallery, setGallery] = useState<string | null>(null); const [filter, setFilter] = useState("All");
  const filteredMedia = useMemo(() => filter === "All" ? media : filter === "Furniture" ? media.slice(0, 3) : media.slice(3), [filter]);
  const go = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
  return <div className="wsl-site"><Nav onNavigate={go} />
    <main>
      <section id="home" className="hero"><img src={heroImage} alt="Contemporary luxury home in Abuja" /><div className="hero-shade"/><div className="hero-copy"><span className="eyebrow light">WSL PROPERTIES / ABUJA</span><h1>Luxury homes,<br/><em>built with craft.</em></h1><p>We develop considered spaces for living well — from the first line on paper to the final finish.</p><div className="hero-actions"><Button onClick={() => go("properties")}>View properties <ArrowUpRight size={16}/></Button><button className="text-link light" onClick={() => go("updates")}><span className="play"><Play size={12} fill="currentColor"/></span> See our progress</button></div></div><div className="hero-meta"><span>01 — 03</span><span>Scroll to explore ↓</span></div></section>
      <section id="properties" className="section properties-section"><SectionIntro eyebrow="A considered collection" title="Properties for living well." text="Every WSL home is shaped by its setting, finished with intention and made to last."/><div className="property-grid">{properties.map(p => <article className="property-card" key={p.id}><div className="property-image"><img src={p.image} alt={p.name}/><span className="property-number">{p.id}</span><button onClick={() => setGallery(p.image)} aria-label={`View ${p.name}`}><ArrowUpRight size={20}/></button></div><div className="property-info"><div><h3>{p.name}</h3><p>{p.type} · {p.location}</p></div><strong>{p.price}</strong></div><div className="feature-row">{p.features.map(f => <span key={f}>{f}</span>)}</div></article>)}</div><div className="section-link"><button className="text-link" onClick={() => go("contact")}>View all properties <ArrowUpRight size={16}/></button></div></section>
      <section id="about" className="section about-section"><div className="about-image"><img src={furniture1} alt="Crafted interior detail"/><span className="image-caption">Material, proportion, light.</span></div><div className="about-copy"><SectionIntro eyebrow="Our approach" title="Built on craft. Shaped by experience." text="WSL Properties is a Nigerian property development company with roots in making. We bring the same discipline, detail and care to every home we deliver."/><div className="timeline"><div><b>01</b><span>Founded</span></div><div><b>02</b><span>Bespoke furniture</span></div><div className="active"><b>03</b><span>Real estate</span></div><div><b>04</b><span>Today</span></div></div><button className="text-link" onClick={() => go("contact")}>More about WSL <ArrowUpRight size={16}/></button></div></section>
      <section id="updates" className="project-feature"><div className="project-image"><img src={property3} alt="Arya Luxe construction progress"/><span className="project-label">Currently building</span></div><div className="project-copy"><span className="eyebrow">Ongoing project / 2025—26</span><h2>Arya Luxe,<br/><em>Gwarinpa.</em></h2><p>A private collection of contemporary residences, being built with clarity, quality and a long view.</p><div className="progress-line"><span style={{ width: "42%" }}/></div><div className="progress-meta"><span>Current stage</span><strong>Block Work <small>42%</small></strong></div><button className="text-link" onClick={() => go("arya")}>Follow the build <ArrowUpRight size={16}/></button></div></section>
      <section id="jobs" className="section jobs-section"><SectionIntro eyebrow="The work behind the work" title="Made before. Made well." text="A selection of spaces, details and objects from our previous work."/><div className="filter-tabs">{["All", "Photos", "Furniture", "Build"].map(x => <button className={filter === x ? "active" : ""} onClick={() => setFilter(x)} key={x}>{x}</button>)}</div><div className="media-grid">{filteredMedia.map((src, i) => <button key={src} className={`media-item media-${i}`} onClick={() => setGallery(src)}><img src={src} alt="WSL Properties previous work"/><span><ArrowUpRight size={18}/></span></button>)}</div></section>
      <section id="arya" className="section journal-section"><SectionIntro eyebrow="Construction journal" title="Follow Arya Luxe over time." text="Real progress, documented from the ground up."/><div className="stage-tabs">{stages.map((stage, i) => <button className={selectedStage === i ? "active" : ""} onClick={() => setSelectedStage(i)} key={stage}><span>0{i + 1}</span>{stage}</button>)}</div><div className="journal-detail"><img src={property2} alt={`${stages[selectedStage]} at Arya Luxe`}/><div><span className="eyebrow">Stage 0{selectedStage + 1} / Arya Luxe</span><h3>{stages[selectedStage]}</h3><p>{selectedStage === 1 ? "Block work completed through level 2. The structure is taking shape with clean lines and a generous relationship to light." : "The team is progressing carefully through this milestone, keeping the quality of the build at the centre of every decision."}</p><div className="journal-meta"><span>Latest report</span><strong>14 September 2025</strong><span>Next step</span><strong>{stages[Math.min(selectedStage + 1, stages.length - 1)]}</strong></div></div></div></section>
      <section id="contact" className="contact-section"><div><SectionIntro eyebrow="Start a conversation" title="Let's find the right place for you." text="For property enquiries, project information or partnerships, our team is ready to help."/><div className="contact-details"><a href="mailto:mailwaro.online@gmail.com"><Mail size={18}/>mailwaro.online@gmail.com</a><a href="tel:+2349010883999"><Phone size={18}/>+234 901 088 3999</a><span><MapPin size={18}/>Gwarinpa, Abuja, Nigeria</span></div></div><form onSubmit={e => { e.preventDefault(); alert("Thank you. A member of our team will be in touch shortly."); }}><Input placeholder="Full name" required/><Input placeholder="Phone number" required/><Input type="email" placeholder="Email address" required/><Input placeholder="Interested in"/><Textarea placeholder="Tell us a little about what you are looking for"/><Button type="submit">Send enquiry <ArrowUpRight size={16}/></Button></form></section>
    </main><footer><div className="wordmark"><img src={logo} alt="WSL Properties"/><span>WSL <b>PROPERTIES</b></span></div><p>Luxury homes, built with craft.</p><div className="footer-social"><a href="#contact"><Instagram size={18}/></a><a href="#contact"><Facebook size={18}/></a><a href="mailto:mailwaro.online@gmail.com"><Mail size={18}/></a></div><small>© 2025 WSL Properties. All rights reserved.</small></footer>{gallery && <div className="lightbox" onClick={() => setGallery(null)}><button onClick={() => setGallery(null)} aria-label="Close"><X/></button><img src={gallery} alt="Expanded WSL project"/></div>}</div>
}

export function AdminPreview() { const [updates, setUpdates] = useState(["Block work completed, level 2", "Ceiling installation started"]); const [caption, setCaption] = useState(""); return <div className="admin-shell"><aside><div className="wordmark"><span>WSL <b>ADMIN</b></span></div>{["Overview", "Project Updates", "Previous Jobs", "Properties", "About Us"].map((x, i) => <button className={i === 1 ? "active" : ""} key={x}>{x}</button>)}</aside><section className="admin-main"><div className="admin-top"><span>Project updates</span><span>Admin / WSL Properties</span></div><div className="admin-heading"><div><span className="eyebrow">Arya Luxe / Gwarinpa</span><h1>Project updates</h1></div><Button><Plus size={16}/> New update</Button></div><div className="admin-grid"><div className="publish-panel"><h3>Publish an update</h3><p>Share a moment from the build.</p><div className="upload-box"><Upload size={24}/><strong>Upload media</strong><span>Photos or videos, up to 10MB</span></div><Textarea value={caption} onChange={e => setCaption(e.target.value)} placeholder="Write a caption..."/><select defaultValue="Block Work"><option>Foundation</option><option>Block Work</option><option>Ceiling</option><option>Windows</option><option>Finishing</option></select><Button onClick={() => { if(caption) { setUpdates([caption, ...updates]); setCaption(""); } }}>Publish update</Button></div><div className="feed-panel"><h3>Published updates <span>{updates.length}</span></h3>{updates.map((u, i) => <div className="feed-item" key={`${u}-${i}`}><div><strong>{u}</strong><span>Today · 10:42 · Block Work</span></div><button onClick={() => setUpdates(updates.filter((_, j) => j !== i))}><Trash2 size={16}/></button></div>)}</div></div></section></div> }

export { properties, stages };
